### PR TITLE
fix undefined error when build without docker, add essential includes

### PR DESCRIPTION
**Pull request by lucasjinreal**

### CODE REVIEW

**Comment by byshiue** [comment]
Please reverse the files that should not be changed.

**Comment by jinfagang** [comment]
@byshiue Hi, there are 3 main modification here:

1. .vscode  -> which should be revert;
2. added essential include in .cu;
3. added manually -lcublasLt which caused undefined error.

Which part would u like to revert further?

**Comment by byshiue** [comment]
All files which don't help fix the bug you encounter.

**Comment by jinfagang** [comment]
Close this, since I have to change :+1: 

```
# find_package(CUDA 10.2 REQUIRED)
find_package(CUDA REQUIRED)
```
to make it work on my env which might breaks main branch.

**Pull request closed without merging**
